# ITP11701 Introduction to AI Programming II, Spring 2021
# Lab session 01: NumPy practice (Mar.12)

## Goals 
   In this Lab session, you practice writing Python `NumPy` library. 
   
   Most of the linear algebra compuations can be done by functions in Numpy library with a very simple and efficient manner.

Today's Issues:
  1. Why NumPy and Not Python lists
  2. How to create NumPy Arrays
  3. Create N-Dimensional Array
  4. Mathematical Operations and Array Calculations 

## 1. Why NumPy and Not Python lists
   

NumPy provides efficient storage and better ways of handling data for Mathematical Operations.

NumPy is the fundamental package for scientific computing with Python. Extremely useful!!

links used:
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html    

## 2. How to create NumPy Arrays

 - Import the "numpy" library as "np"

In [2]:
import numpy as np
print(np.__version__)

1.19.5


- Use `np.array(....)` function for creating a numpy array

In [3]:
np_arr = np.array([1,2,3,4,5,6])

In [4]:
np_arr  #  print(np_arr)

array([1, 2, 3, 4, 5, 6])

- How about a `python list` with the same contents?

In [5]:
py_arr = [1,2,3,4,5,6]

In [7]:
py_arr

[1, 2, 3, 4, 5, 6]

- Check the difference between python array and numpy array

In [12]:
py_arr = [1,2,3,4, "Hi",5,6] #heterogenuous

In [13]:
py_arr

[1, 2, 3, 4, 'Hi', 5, 6]

In [20]:
[type(item) for item in py_arr]

[int, int, int, int, str, int, int]

In [14]:
np_arr = np.array([1,2,3, "bye",4,5,6])  #homogenous

In [15]:
np_arr

array(['1', '2', '3', 'bye', '4', '5', '6'], dtype='<U21')

In [21]:
[type(item) for item in np_arr]

[numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_,
 numpy.str_]

 - Create a list with values 1 to 10 and assign it to the variable "list1"
 - Create an integer array from list1 and assign it
 - Check the data type of each array (use the attribute "dtype")

In [22]:
list1= range(1, 11)
np_arr = np.array(list1, dtype = np.int16)   # np_arr = np.array(list1, "i") 
print(np_arr, np_arr.dtype)

[ 1  2  3  4  5  6  7  8  9 10] int16


In [27]:
array1 = np.arange(1,11, dtype = np.int16)
print(array1)

[ 1  2  3  4  5  6  7  8  9 10]


 - Create a list with values 1 to 10 and assign it to the variable "list1"
 - Create an array of floats from list1 and assign it
 - Check the data type of each array (use the attribute "dtype")

In [ ]:
list1= range(1, 11)
np_arr = np.array(list1, dtype = np.float64)   # np_arr = np.array(list1, "i") 
print(np_arr, np_arr.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.] float64


## 3. Create N-Dimensional Array

- Use `np.array()` and many other function for creating a numpy array
- Use `np.reshape()` function   for reshaping the array without changing the original elemets
- Use `np.arange()` function for creating sequence of numbers in array
- Use `np.empty()` function to get an array with uninitialized (artibrary) elements
- Use `np.zeros()` and `np.ones()` functions for creating numpy arrays whose contents are all zeros or ones
- Use `np.diag()` function for creating a diagonal matrix
- Use `np.ravel()` function for flatting a given array

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://www.oreilly.com/library/view/elegant-scipy/9781491922927/assets/elsp_0105.png'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

In [65]:
import numpy as np
np_arr=np.arange(0,10,1)
np_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://t1.daumcdn.net/cfile/tistory/99B4C23C5A884A392C'><script type="application/vnd.jupyter-embedded-widgets">{}</script>

In [66]:
np_arr.reshape(2,5) #2 by 5

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [67]:
print(np_arr)

[0 1 2 3 4 5 6 7 8 9]


In [68]:
np.reshape(np_arr,(2,5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [51]:
np_arr = np.empty((5,2))
print(np_arr)

[[4.63787362e-310 2.17388884e-322]
 [2.12199579e-314 3.44620186e-085]
 [4.34900767e+199 1.87422380e+261]
 [4.56782417e-085 2.51968629e+180]
 [1.19480757e+190 9.54596908e-307]]


In [58]:
np_arr=np.empty((5,2), dtype = np.int8)
print(np_arr)

[[64 85]
 [16 46]
 [96 85]
 [ 0  0]
 [ 3  0]]


In [60]:
np_arr = np.zeros((5,2)) # Create an array of all zeros
print(np_arr)

[[0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


In [70]:
np_arr = np.ones((5,2), dtype = np.int8)  # Create an array of all ones
print(np_arr)

[[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]


In [77]:
np_arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(np_arr)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [82]:
np_arr.ravel(order='C')

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [83]:
np_arr.ravel(order='F')

array([ 1,  5,  9,  2,  6, 10,  3,  7, 11,  4,  8, 12])

In [87]:
np.eye(3, dtype=np.int8) # 3 by b matrics

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]], dtype=int8)

In [89]:
np.full((2,3), 7)  # Create a constant array

array([[7, 7, 7],
       [7, 7, 7]])

#### Practice 1
- Create an array of shape (2,3,4) of zeros
- Create an array of shape (3,4,5) of ones
- Create an array with values 0 to 49 using the np.arange() 

In [90]:
import numpy as np
np_arr=np.zeros((2,3,4))
print(np_arr)
np_arr = np.ones((3, 4, 5))
print(np_arr)
np_arr = np.arange(50)
print(np_arr)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49]


#### Practice  2    
- Create an array of from the list [2,5,5, -7.2, 3,5, 2.7, 4.7] and assign it 
  print np_arr[1] 
- try printing np_arr[1:4] to print the 1st element to 3rd element.
- Create a 2-D array from the following list and assign it 
  [[2, 3.2, 5.5, -6.4, -2.2, 2.4], 
  [1, 22, 4, 0.1, 5.3, -9], 
  [3, 1, 2.1, 21, 1.1, -2]]

- try printing the following
  a[:, 3], 
  a[1:4, 0:4], 
  a[1:, 2] 

In [98]:
import numpy as np
np_arr = np.array([2,5.5, -7.2, 3.5, 2.7, 4.7])
print(np_arr)

[ 2.   5.5 -7.2  3.5  2.7  4.7]


In [100]:
np_arr[1]

5.5

In [107]:
np_arr[1:4]

array([ 5.5, -7.2,  3.5])

In [108]:
np_arr = np.array([[2, 3.2, 5.5, -6.4, -2.2, 2.4],
                [1, 22, 4, 0.1, 5.3, -9],
                [3, 1, 2.1, 21, 1.1, -2]])
print(np_arr)

[[ 2.   3.2  5.5 -6.4 -2.2  2.4]
 [ 1.  22.   4.   0.1  5.3 -9. ]
 [ 3.   1.   2.1 21.   1.1 -2. ]]


In [109]:
np_arr[:,3]

array([-6.4,  0.1, 21. ])

In [112]:
np_arr[1:3, 3:5]

array([[ 0.1,  5.3],
       [21. ,  1.1]])

#### POPCORN QUIZ (Do it yourself)
Write a Python program to create a 2d array with 1s on the border and 0s on the inside.
- Sample Output

 Original array:     
 
    [[ 1.  1.  1.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]]  
 
 result in below:
 
    [[ 1.  1.  1.  1.  1.]                                                  
 [ 1.  0.  0.  1.  1.]                                                  
 [ 1.  0.  0.  1.  1.]                                                  
 [ 1.  0.  0.  1.  1.]                                                  
 [ 1.  1.  1.  1.  1.]]

In [ ]:
import numpy as np  # itp11704
np_arr = np.ones((5,5))
print(np_arr)
# write your answer in here
np_arr[1:4, 1:3] = np.zeros((3,2))
print(np_arr)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 0. 0. 1. 1.]
 [1. 1. 1. 1. 1.]]


#### Practice 3
- Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)).

- Check the `shape`, the `size`,n the maximum and minimum elements of the array 

In [117]:
import numpy as np
np_arr=np.array([range(4),range(10,14)])
print(np_arr)
print(np_arr.shape) # return the shape of a given array
print(np_arr.size)  # size returns the total number of elemets in a given array
print(np_arr.ndim)  # returns the dimension of a given array
print(np_arr.max())
print(np_arr.min())

[[ 0  1  2  3]
 [10 11 12 13]]
(2, 4)
8
2
13
0


- Contiunue to use the array as defined above. 
- print the array which is reshaped by (4,2)
- print the array transposed
- print the array flattened to a single dimension

In [122]:
np.reshape(np_arr,(4,2))
print(np_arr)
print(np.transpose(np_arr))  # Recall 'transpose' in our 1st lecture
print(np.ravel(np_arr))

[[ 0  1  2  3]
 [10 11 12 13]]
[[ 0 10]
 [ 1 11]
 [ 2 12]
 [ 3 13]]
[ 0  1  2  3 10 11 12 13]


## 4. Mathematical Operations and Array Calculations 

NumPy n-dimensional arrays makes it extremely easy to perform mathematical operations on it.
- Mathematical operations with arrays
- Mathematical operations mixing scalars and arrays
- Comparison operators and Boolean operations on arrays
- Broadcasting

In [123]:
py_arr = [1,2,3] * 2

In [124]:
np_arr = np.array([1,2,3]) * 2 

In [125]:
py_arr  # python list repeats the same list twice (*2 does not mean arithmetic multiplication)

[1, 2, 3, 1, 2, 3]

In [127]:
np_arr  # numpy array works for arithmetic multiplication

array([2, 4, 6])

multi dimensional mathematical operations

In [130]:
np_arr = np.ones((5,2)) * 10
print(np_arr)

[[10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]
 [10. 10.]]


#### Practice 4
- Create a 2-D array of shape (2, 4) containing two lists (range(4), range(10, 14)) and assign it to the   
  variable "a" 
- Create an array from a list [2, -1, 1, 0] and assign it to the variable "b"
- Multiply array "a" by "b" and view the result. Do you understand how NumPy has used its broadcasting feature
  to do the calculation even though the arrays are different shapes?

In [131]:
import numpy as np

In [132]:
a = np.array([range(4), range(10,14)])
a

array([[ 0,  1,  2,  3],
       [10, 11, 12, 13]])

In [133]:
b = np.array([2,-1,1,0])
b

array([ 2, -1,  1,  0])

In [135]:
# a*b
print(a*b)  # a*b returns a matrix whose the first row is element-wise multiplication of a[1,:] and b and the second row is element-wise multiplication of a[2,:] and b

[[  0  -1   2   0]
 [ 20 -11  12   0]]


### Broadcasting 
Broadcasting is simply a set of rules for applying binary ufuncs (e.g., addition, subtraction, multiplication, etc.) on arrays of different sizes.


In [139]:
import numpy as np

In [140]:
a = np.array([0,1,2])
b = np.array([5,5,5])

In [141]:
a+b

array([5, 6, 7])

Broadcasting allows these types of binary operations to be performed on arrays of different sizes–for example,
you can just as easily add a scalar (think of it as a zero-dimensional array) to an array:

In [142]:
a+5

array([5, 6, 7])



You can think of this as an operation that stretches or duplicates the value 5 into the array [5, 5, 5], and adds the results. The advantage of NumPy's broadcasting is that this duplication of values does not actually take place, but it is a useful mental model as we think about broadcasting.

You can similarly extend this to arrays of higher dimension. Observe the result when we add a one-dimensional array to a two-dimensional array:


In [144]:
c = np.ones((3,3))
print(c)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [ ]:
c + a # recall that the shape of c is (3,3) and the shape of a is (1,3)
      # Then a is 'broadcasted' to have the shape (3,3) and added to c.

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

<script src="https://npmcdn.com/jupyter-js-widgets@~1.2.0/dist/embed.js"></script><img src='https://jakevdp.github.io/PythonDataScienceHandbook/figures/02.05-broadcasting.png'><script type="application/vnd.jupyter-embedded-widgets">{}</script>


The light boxes represent the broadcasted values: again, this extra memory is not actually allocated in the course of the operation, but it can be useful conceptually to imagine that it is.

### Rules of Broadcasting

In [146]:
a = np.ones((2,3))
print(a)
b = np.arange(3)
print(b)

[[1. 1. 1.]
 [1. 1. 1.]]
[0 1 2]


In [147]:
s1 = a.shape
print(s1)
s2 = b.shape
print(s2)

(2, 3)
(3,)


In [148]:
s = a+b
print(s)
s.shape

[[1. 2. 3.]
 [1. 2. 3.]]


(2, 3)

In [151]:
a = np.arange(3).reshape((3,1))
b = np.arange(3)
print(a)
print(b)

[[0]
 [1]
 [2]]
[0 1 2]


In [152]:
a+b

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [153]:
a = np.ones((3,2))
print(a)
b = np.arange(3)
print(b)

[[1. 1.]
 [1. 1.]
 [1. 1.]]
[0 1 2]


In [154]:
a + b

ValueError: ignored

Thanks for your attention!!! 